/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: matousekfoto (https://sketchfab.com/matousekfoto)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-globe-98d2b04d46474bafb4250cc75dc583b3
Title: Earth Globe 🌍
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame, useThree} from '@react-three/fiber';
import GlobeScene from '../models/globe.jsx';

function Globe(props) {
  const GlobeRef = useRef();
  const { nodes, materials } = useGLTF(GlobeScene);
  return (
    <group ref={GlobeRef} {...props}>
      <group position={[-5.177, -20.679, 0]} rotation={[Math.PI / 2, -0.462, Math.PI]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.meshNode_Material_u1_v1_0.geometry}
            material={materials.Material_u1_v1} />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.meshNode_Material_u2_v1_0.geometry}
            material={materials.Material_u2_v1} />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.meshNode_Material_u1_v2_0.geometry}
            material={materials.Material_u1_v2} />
        </group>
      </group>
    </group>
  );
}
export const Globe = () => {
  earth_globe.glb
};
